# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# Example of deploying with poetry: https://testdriven.io/tips/810f9bb5-c9df-479d-baa4-290c7e0779f1/

name: Python Code Tests

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # python-version: ["3.8", "3.9", "3.10"]
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install libsqlcipher-dev
        python -m pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Black Formatter
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python -m pip install black
        black .
    - name: Test with pytest
      env:
        PYTHONPATH: .
      run: |
        pytest

